import type { IconType } from "react-icons";
import { FaReact, FaHtml5, FaCss3Alt, FaGit } from "react-icons/fa";
import {
  SiTypescript,
  SiJavascript,
  SiTailwindcss,
  SiVite,
  SiEslint,
  SiPrettier,
  SiPnpm,
  SiBun,
  SiFlutter,
  SiFramer,
  SiZod,
  SiAxios,
  SiRadixui,
  SiPayloadcms,
} from "react-icons/si";
import {
  TbRoute,
  TbDatabase,
  TbTable,
  TbInfinity,
  TbHandGrab,
  TbAtom2,
  TbLanguage,
  TbComponents,
  TbLayoutDashboard,
  TbClipboardList,
  TbCalendar,
  TbApi,
  TbCode,
  TbBraces,
  TbAlertTriangle,
  TbGitBranch,
  TbGitCommit,
  TbFilter,
  TbNetwork,
  TbCashRegister,
  TbWorld,
} from "react-icons/tb";

export const skillIcons: Record<string, IconType> = {
  "React.js": FaReact,
  TypeScript: SiTypescript,
  "JavaScript (ES6+)": SiJavascript,
  HTML5: FaHtml5,
  CSS3: FaCss3Alt,
  "Tailwind CSS": SiTailwindcss,

  "TanStack Router": TbRoute,
  "TanStack Query": TbDatabase,
  "TanStack Table": TbTable,
  "TanStack Form": TbClipboardList,
  "TanStack Virtual": TbInfinity,
  "dnd-kit": TbHandGrab,
  Zustand: TbAtom2,
  Zod: SiZod,
  i18n: TbLanguage,
  Motion: SiFramer,
  "React Bits": TbComponents,
  "Shadcn UI": TbLayoutDashboard,
  "Radix UI": SiRadixui,
  "React Hook Form": TbClipboardList,
  "date-fns": TbCalendar,
  Axios: SiAxios,

  "Payload CMS": SiPayloadcms,

  "RESTful API": TbApi,
  "async/await": TbCode,
  "JSON handling": TbBraces,
  "Error handling": TbAlertTriangle,

  "Git & GitHub": FaGit,
  Husky: TbGitBranch,
  ESLint: SiEslint,
  Prettier: SiPrettier,
  "Lint-Staged": TbFilter,
  Commitlint: TbGitCommit,
  Vite: SiVite,
  pnpm: SiPnpm,
  Bun: SiBun,

  "Flutter & Dart": SiFlutter,
  "POS Systems": TbCashRegister,
  "Network Config": TbNetwork,

  Arabic: TbWorld,
  English: TbWorld,
  Turkish: TbWorld,
};
