import type { IconType } from "react-icons";
import { FaReact, FaHtml5, FaCss3Alt, FaGit, FaGithub } from "react-icons/fa";
import { ClaudeIcon } from "./claude-icon";
import {
  SiTypescript,
  SiJavascript,
  SiNextdotjs,
  SiTailwindcss,
  SiVercel,
  SiRailway,
  SiVite,
  SiEslint,
  SiPrettier,
  SiPnpm,
  SiBun,
  SiFlutter,
  SiFramer,
  SiZod,
  SiAxios,
  SiRadixui,
  SiPayloadcms,
  SiReact,
  SiAirtable,
  SiFormik,
} from "react-icons/si";
import {
  TbRoute,
  TbDatabase,
  TbTable,
  TbInfinity,
  TbHandGrab,
  TbAtom2,
  TbLanguage,
  TbComponents,
  TbLayoutDashboard,
  TbClipboardList,
  TbCalendar,
  TbApi,
  TbCode,
  TbBraces,
  TbAlertTriangle,
  TbGitBranch,
  TbGitCommit,
  TbFilter,
  TbNetwork,
  TbCashRegister,
  TbWorld,
  TbMail,
  TbShieldCheck,
} from "react-icons/tb";

export const skillIcons: Record<string, IconType> = {
  "React.js": FaReact,
  "Next.js": SiNextdotjs,
  TypeScript: SiTypescript,
  "JavaScript (ES6+)": SiJavascript,
  HTML5: FaHtml5,
  CSS3: FaCss3Alt,
  "Tailwind CSS": SiTailwindcss,

  "TanStack Router": TbRoute,
  "TanStack Query": TbDatabase,
  "TanStack Table": TbTable,
  "TanStack Form": TbClipboardList,
  "TanStack Virtual": TbInfinity,
  "dnd-kit": TbHandGrab,
  Zustand: TbAtom2,
  Zod: SiZod,
  Yup: TbShieldCheck,
  i18n: TbLanguage,
  Motion: SiFramer,
  "React Bits": TbComponents,
  "Shadcn UI": TbLayoutDashboard,
  "Radix UI": SiRadixui,
  "React Hook Form": TbClipboardList,
  Formik: SiFormik,
  "date-fns": TbCalendar,
  Axios: SiAxios,
  Resend: TbMail,
  Airtable: SiAirtable,

  "React Native": SiReact,
  NativeWind: SiTailwindcss,
  "Reusable React Native": TbComponents,

  "Payload CMS": SiPayloadcms,
  "Neon DB (PostgreSQL)": TbDatabase,
  MongoDB: TbDatabase,

  "RESTful API": TbApi,
  "async/await": TbCode,
  "JSON handling": TbBraces,
  "Error handling": TbAlertTriangle,

  "Git & GitHub": FaGit,
  Vercel: SiVercel,
  Railway: SiRailway,
  Husky: TbGitBranch,
  ESLint: SiEslint,
  Prettier: SiPrettier,
  "Lint-Staged": TbFilter,
  Commitlint: TbGitCommit,
  Vite: SiVite,
  pnpm: SiPnpm,
  Bun: SiBun,

  "Claude AI": ClaudeIcon as IconType,
  "GitHub Copilot": FaGithub,

  "Flutter & Dart": SiFlutter,
  "POS Systems": TbCashRegister,
  "Network Config": TbNetwork,

  Arabic: TbWorld,
  English: TbWorld,
  Turkish: TbWorld,
};
